### PR TITLE
Use new transparent huge pages role and make role able to install MongoDB again

### LINKED ISSUE #22: Unable to install MongoDB with this role
# 🐛 Summary #

This role is currently unable to install MongoDB (3.6) as can be seen in this Actions run: https://github.com/cisagov/ansible-role-mongo/actions/runs/7613233793/job/20732675767#step:8:202. This appears to be a result of the signing key for the apt repository expiring as if you look at https://keyserver.ubuntu.com/pks/lookup?search=2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5&fingerprint=on&op=index you can see that the latest signing key expired on `2023-12-09T16:51:02Z`.

## To reproduce ##

Attempt to use this role to install MongoDB. See that it fails.

## Expected behavior ##

MongoDB 3.6 is successfully installed.

## Any helpful log output or screenshots ##

```console
TASK [ansible-role-mongo : Get mongodb-org GPG key] ****************************
fatal: [debian10-systemd]: FAILED! => {"after": ["B7C5D7D6350947F8", "6ED0E7B82643E131", "254CF3B5AEC0A8F0", "BDE6D2B9216EC7A8", "F8D2585B8783D481", "73A4F27B8DD47936", "0E98404D386FA1D9", "A48449044AAD5C5D", "54404762BBB6E853", "605C66F00D6C9793", "DC30D7C23CBBABEE", "648ACFD622F3D138", "4DFAB270CAA96DFA", "112695A0E562B32A", "DCC9EFBF77E11517", "E0B11894F66AEC98", "04EE7237B7D453EC", "EDA0D2388AE22BA9", "AA8E81B4331F7F50", "EF0F382A1A7B6500"], "before": ["B7C5D7D6350947F8", "6ED0E7B82643E131", "254CF3B5AEC0A8F0", "BDE6D2B9216EC7A8", "F8D2585B8783D481", "73A4F27B8DD47936", "0E98404D386FA1D9", "A48449044AAD5C5D", "54404762BBB6E853", "605C66F00D6C9793", "DC30D7C23CBBABEE", "648ACFD622F3D138", "4DFAB270CAA96DFA", "112695A0E562B32A", "DCC9EFBF77E11517", "E0B11894F66AEC98", "04EE7237B7D453EC", "EDA0D2388AE22BA9", "AA8E81B4331F7F50", "EF0F382A1A7B6500"], "changed": true, "fp": "58712A2291FA4AD5", "id": "2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5", "key_id": "2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5", "msg": "apt-key did not return an error, but failed to add the key (check that the id is correct and *not* a subkey)", "short_id": "91FA4AD5"}
```

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request changes the Ansible code to use the new transparent huge pages role created by @mcdonnnj instead of the old, unsupported one.  It also makes some changes to the Ansible role to allow it to once again install MongoDB.

## 💭 Motivation and context ##

The old THP role used some deprecated Ansible code, which was causing this role to fail its GitHub Actions.

Resolves #22 by making the role once gain able to install MongoDB..

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-approval checklist ##

- [x] Switch to using the default branch of [cisagov/ansible-role-manage-thp](cisagov/ansible-role-manage-thp) once cisagov/ansible-role-manage-thp#4 is merged.

### CODE REVIEW

**Review by dv4harr10 — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍 👍

**Comment by mcdonnnj** [comment]
@jsf9k Would you please update the title of this pull request? There is no mention of changing the apt configuration or fixing the MongoDB installation so I was quite confused when I saw that this PR closed #22.

**Comment by jsf9k** [comment]
> @jsf9k Would you please update the title of this pull request? There is no mention of changing the apt configuration or fixing the MongoDB installation so I was quite confused when I saw that this PR closed #22.

Is that better?  I also made some small updates to the PR description.

**Comment by mcdonnnj** [comment]
> > @jsf9k Would you please update the title of this pull request? There is no mention of changing the apt configuration or fixing the MongoDB installation so I was quite confused when I saw that this PR closed #22.
> 
> Is that better? I also made some small updates to the PR description.

Yep that works for me. Thanks!

**Pull request merged**
